In [12]:
import pandas as pd
# In pandas, there are mainly two datatypes
# one is dataframe which is equivalent to tables in sql
# the other one is series, which is equivakent to a python list
# the columns and rows combines are called dataframe
# the columns are of type series
# Dataframe is a kind of dictionary, in which all the columns are keys,and the series is the value of each key

In [72]:
# To load an excel file we use pd.read_excel
# it returns a dataframe which is similar to table in sql
excel_df = pd.read_excel(r'C:\MyData\MyData\data science\resources\data sets\Attribute DataSet.xlsx')

In [73]:
excel_df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [74]:
# We can have multiple sheets in out excel. 
# By default read_excel reads the first sheet
# In order to read from some other sheet of the same excel file-
pd.read_excel(r'C:\MyData\MyData\data science\resources\data sets\Attribute DataSet.xlsx',sheet_name='Sheet2')

   some value Unnamed: 1 Unnamed: 2  Unnamed: 3
0         NaN        NaN  here also         NaN
1         NaN  some more        NaN         NaN
2         NaN        NaN        NaN  some value

In [75]:
# If we dont want our headers to be a header and want them to be a record, we set header=None while reading excel file
pd.read_excel(r'C:\MyData\MyData\data science\resources\data sets\Attribute DataSet.xlsx',header=None)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
1,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
2,1212192089,Casual,Low,0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
3,1190380701,vintage,High,0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
4,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
497,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
498,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
499,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
500,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [76]:
# If we want, we can give column name by our self as well-
pd.read_excel(r'C:\MyData\MyData\data science\resources\data sets\Attribute DataSet.xlsx',header=None,sheet_name='Sheet2',names=['first','second','third','fourth'])

        first     second      third      fourth
0  some value        NaN        NaN         NaN
1         NaN        NaN  here also         NaN
2         NaN  some more        NaN         NaN
3         NaN        NaN        NaN  some value

In [78]:
excel_df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [79]:
# head(n)-> To show first n rows
# By default it shows first 5 rows
excel_df.head()

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0

In [80]:
excel_df.head(2)

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0

In [81]:
# tail(n)-> To show last n rows
# By default it shows last 5 rows
excel_df.tail()

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [82]:
excel_df.tail(2)

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [83]:
pd.read_csv(r'C:\MyData\MyData\data science\resources\data sets\haberman.csv')

     30  64   1  1.1
0    30  62   3    1
1    30  65   0    1
2    31  59   2    1
3    31  65   4    1
4    33  58  10    1
..   ..  ..  ..  ...
300  75  62   1    1
301  76  67   0    1
302  77  65   3    1
303  78  65   1    2
304  83  58   2    2

[305 rows x 4 columns]

In [84]:
csv_df = pd.read_csv(r'C:\MyData\MyData\data science\resources\data sets\@seofile.txt',header=None,sep='@',names=['Age','year of operation','positive axillary nodes detected','Survival status'])

In [85]:
# We can use datasets which are present online
# If datasets are present on github, we can use it without downloading
# Click on the dataset, then click on "row" option, copy the url and paste here
pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/Smarket.csv")

      Year   Lag1   Lag2   Lag3   Lag4   Lag5   Volume  Today Direction
0     2001  0.381 -0.192 -2.624 -1.055  5.010  1.19130  0.959        Up
1     2001  0.959  0.381 -0.192 -2.624 -1.055  1.29650  1.032        Up
2     2001  1.032  0.959  0.381 -0.192 -2.624  1.41120 -0.623      Down
3     2001 -0.623  1.032  0.959  0.381 -0.192  1.27600  0.614        Up
4     2001  0.614 -0.623  1.032  0.959  0.381  1.20570  0.213        Up
...    ...    ...    ...    ...    ...    ...      ...    ...       ...
1245  2005  0.422  0.252 -0.024 -0.584 -0.285  1.88850  0.043        Up
1246  2005  0.043  0.422  0.252 -0.024 -0.584  1.28581 -0.955      Down
1247  2005 -0.955  0.043  0.422  0.252 -0.024  1.54047  0.130        Up
1248  2005  0.130 -0.955  0.043  0.422  0.252  1.42236 -0.298      Down
1249  2005 -0.298  0.130 -0.955  0.043  0.422  1.38254 -0.489      Down

[1250 rows x 9 columns]

In [87]:
# We can read data present on browser by using read_html
# The return type here is list as there can be multiple data sets available on the browser
html_df = pd.read_html('https://www.basketball-reference.com/leagues/NBA_2015_totals.html')

In [88]:
type(html_df)

list

In [90]:
html_df[0]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [93]:
# Likewise we can read json data as well
json_df = pd.read_json("https://api.github.com/repos/pandas-dev/pandas/issues")

In [94]:
type(json_df)

pandas.core.frame.DataFrame

In [102]:
json_df

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,closed_at,author_association,active_lock_reason,draft,pull_request,body,reactions,timeline_url,performed_via_github_app,state_reason
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48076,1338141236,PR_kwDOAA0YD849I12_,48076,Backport PR #48065 on branch 1.4.x (CI/DEPS: F...,...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Backport PR #48065: CI/DEPS: Fix timezone test...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48075,1338134330,PR_kwDOAA0YD849I0nB,48075,TST: Address test warnings,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] [Tests added and passed](https://pandas....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48074,1338058865,I_kwDOAA0YD85PwShx,48074,BUG: subclassing `CustomBusinessDay` returns i...,...,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48073,1338050324,PR_kwDOAA0YD849IlCa,48073,DEPR: `sort_columns` in `plot` (#47563),...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #47563\r\n- [x] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48072,1338028799,PR_kwDOAA0YD849Ihiv,48072,TST: Check dtype in test_resample_empty_dataframe,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48071,1337983698,I_kwDOAA0YD85PwALS,48071,ENH: Avoid casting to int64/uint64 for GroupBy...,...,NaT,MEMBER,NaN,NaN,NaN,"Currently, we are casting the arrays to int64/...",{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48070,1337982848,PR_kwDOAA0YD849IY0T,48070,ENH: Support mask in GroupBy.cumsum,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] xref #37493 (Replace xxxx with the Githu...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48069,1337952004,PR_kwDOAA0YD849IS0r,48069,Create pr action/pre commit config update 0,...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #48061\r\n- [ ] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48067,1337810498,PR_kwDOAA0YD849H3_e,48067,TST: Check index when grouping all columns of ...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #32464\r\n- [x] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48066,1337754311,PR_kwDOAA0YD849HsCV,48066,CI: Avoid flaky build errors & show installed ...,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,xref #47305 & https://github.com/pandas-dev/pa...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48064,1337620886,PR_kwDOAA0YD849HQTB,48064,BUG: Groupby cumprod nan influences other colu...,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48063,1337572051,PR_kwDOAA0YD849HFbB,48063,fixed docstring error with pandas.Series.plot....,...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,When you run python `./scripts/validate_docstr...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48062,1337530690,PR_kwDOAA0YD849G8pe,48062,REF: make copy keyword non-stateful,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48061,1337518944,I_kwDOAA0YD85PuOtg,48061,STYLE: upgrade flake8,...,NaT,MEMBER,NaN,NaN,NaN,Issue here is:\r\n1. checkout the `create-pr-a...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48060,1337411497,I_kwDOAA0YD85Pt0ep,48060,"DOC: ""Creating a Python environment"" in ""Creat...",...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48058,1337297494,PR_kwDOAA0YD849GKle,48058,REGR: fix reset_index (Index.insert) regressio...,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #47071\r\n- [x] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48057,1337202881,PR_kwDOAA0YD849F2qL,48057,REGR: fix regression in scalar setitem with se...,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #46268\r\n- [x] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48056,1337153682,I_kwDOAA0YD85Ps1iS,48056,BUG: Rolling operations on groupby with apply ...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48055,1337049837,PR_kwDOAA0YD849FVb2,48055,"Fixed docstring error with style.py, unknown p...",...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,When you run python` ./scripts/validate_docstr...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48052,1336615868,I_kwDOAA0YD85PqyO8,48052,BUG: Weird Behavior of astype(bool) for np.nan,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48051,1336597202,PR_kwDOAA0YD849D1fa,48051,REF: dont alter self in _validate_specification,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,"Besides being better-practice, this will make ...",{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48050,1336561687,PR_kwDOAA0YD849Dt3t,48050,ENH: allow user to infer SAS file encoding; ad...,...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #48048 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48048,1336561147,I_kwDOAA0YD85Pqk37,48048,ENH: Add option to `read_sas` to infer encodin...,...,NaT,NONE,NaN,NaN,NaN,### Feature Type\r\n\r\n- [X] Adding new funct...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48046,1336517413,I_kwDOAA0YD85PqaMl,48046,CI: setuptools 64.0.0 breaks our builds,...,NaT,MEMBER,NaN,NaN,NaN,This is one of the failing builds:\r\n\r\nhttp...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48042,1336470117,PR_kwDOAA0YD849DaTk,48042,TST: GH39984 Addition to tests,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #39984 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48041,1336388945,PR_kwDOAA0YD849DJbw,48041,CI: Include FutureWarning from numpy in npdev ...,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] [Tests added and passed](https://pandas....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48039,1336263864,I_kwDOAA0YD85PpcS4,48039,Unclear error statement printed when `python ....,...,NaT,NONE,NaN,NaN,NaN,When I run `python ./scripts/validate_docstrin...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48038,1336003792,I_kwDOAA0YD85PoczQ,48038,ENH: Improve styling compatibility with Latex,...,NaT,NONE,NaN,NaN,NaN,### Feature Type\n\n- [X] Adding new functiona...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48035,1335691411,I_kwDOAA0YD85PnQiT,48035,"DOC: ""Committing your code"" in ""Contributing t...",...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48034,1335543885,I_kwDOAA0YD85PmshN,48034,BUG: `Series.replace` converts `np.nan` into `...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN

In [95]:
json_df.columns

Index(['url', 'repository_url', 'labels_url', 'comments_url', 'events_url',
       'html_url', 'id', 'node_id', 'number', 'title', 'user', 'labels',
       'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments',
       'created_at', 'updated_at', 'closed_at', 'author_association',
       'active_lock_reason', 'draft', 'pull_request', 'body', 'reactions',
       'timeline_url', 'performed_via_github_app', 'state_reason'],
      dtype='object')

In [96]:
json_df['url']

0     https://api.github.com/repos/pandas-dev/pandas...
1     https://api.github.com/repos/pandas-dev/pandas...
2     https://api.github.com/repos/pandas-dev/pandas...
3     https://api.github.com/repos/pandas-dev/pandas...
4     https://api.github.com/repos/pandas-dev/pandas...
5     https://api.github.com/repos/pandas-dev/pandas...
6     https://api.github.com/repos/pandas-dev/pandas...
7     https://api.github.com/repos/pandas-dev/pandas...
8     https://api.github.com/repos/pandas-dev/pandas...
9     https://api.github.com/repos/pandas-dev/pandas...
10    https://api.github.com/repos/pandas-dev/pandas...
11    https://api.github.com/repos/pandas-dev/pandas...
12    https://api.github.com/repos/pandas-dev/pandas...
13    https://api.github.com/repos/pandas-dev/pandas...
14    https://api.github.com/repos/pandas-dev/pandas...
15    https://api.github.com/repos/pandas-dev/pandas...
16    https://api.github.com/repos/pandas-dev/pandas...
17    https://api.github.com/repos/pandas-dev/pandas...
18    https://api.github.com/repos/pandas-dev/pandas...
19    https://api.github.com/repos/pandas-dev/pandas...
20    https://api.github.com/repos/pandas-dev/pandas...
21    https://api.github.com/repos/pandas-dev/pandas...
22    https://api.github.com/repos/pandas-dev/pandas...
23    https://api.github.com/repos/pandas-dev/pandas...
24    https://api.github.com/repos/pandas-dev/pandas...
25    https://api.github.com/repos/pandas-dev/pandas...
26    https://api.github.com/repos/pandas-dev/pandas...
27    https://api.github.com/repos/pandas-dev/pandas...
28    https://api.github.com/repos/pandas-dev/pandas...
29    https://api.github.com/repos/pandas-dev/pandas...
Name: url, dtype: object

In [97]:
json_df['user']

0     {'login': 'meeseeksmachine', 'id': 39504233, '...
1     {'login': 'mroeschke', 'id': 10647082, 'node_i...
2     {'login': 'attack68', 'id': 24256554, 'node_id...
3     {'login': 'YagoGG', 'id': 7356565, 'node_id': ...
4     {'login': 'rhshadrach', 'id': 45562402, 'node_...
5     {'login': 'phofl', 'id': 61934744, 'node_id': ...
6     {'login': 'phofl', 'id': 61934744, 'node_id': ...
7     {'login': 'jmoro0408', 'id': 66977019, 'node_i...
8     {'login': 'YagoGG', 'id': 7356565, 'node_id': ...
9     {'login': 'mroeschke', 'id': 10647082, 'node_i...
10    {'login': 'phofl', 'id': 61934744, 'node_id': ...
11    {'login': 'joshuabello2550', 'id': 43732414, '...
12    {'login': 'jbrockmendel', 'id': 8078968, 'node...
13    {'login': 'MarcoGorelli', 'id': 33491632, 'nod...
14    {'login': 'marenwestermann', 'id': 17019042, '...
15    {'login': 'jorisvandenbossche', 'id': 1020496,...
16    {'login': 'jorisvandenbossche', 'id': 1020496,...
17    {'login': 'jtho123', 'id': 111128123, 'node_id...
18    {'login': 'joshuabello2550', 'id': 43732414, '...
19    {'login': 'redreamality', 'id': 3147776, 'node...
20    {'login': 'jbrockmendel', 'id': 8078968, 'node...
21    {'login': 'YYYasin19', 'id': 26421646, 'node_i...
22    {'login': 'YYYasin19', 'id': 26421646, 'node_i...
23    {'login': 'phofl', 'id': 61934744, 'node_id': ...
24    {'login': 'BarkotBeyene', 'id': 38720673, 'nod...
25    {'login': 'mroeschke', 'id': 10647082, 'node_i...
26    {'login': 'joshuabello2550', 'id': 43732414, '...
27    {'login': 'vnmabus', 'id': 2364173, 'node_id':...
28    {'login': 'marenwestermann', 'id': 17019042, '...
29    {'login': 'ng-henry', 'id': 104644400, 'node_i...
Name: user, dtype: object

In [98]:
json_df['user'][0]

{'login': 'meeseeksmachine',
 'id': 39504233,
 'node_id': 'MDQ6VXNlcjM5NTA0MjMz',
 'avatar_url': 'https://avatars.githubusercontent.com/u/39504233?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/meeseeksmachine',
 'html_url': 'https://github.com/meeseeksmachine',
 'followers_url': 'https://api.github.com/users/meeseeksmachine/followers',
 'following_url': 'https://api.github.com/users/meeseeksmachine/following{/other_user}',
 'gists_url': 'https://api.github.com/users/meeseeksmachine/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/meeseeksmachine/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/meeseeksmachine/subscriptions',
 'organizations_url': 'https://api.github.com/users/meeseeksmachine/orgs',
 'repos_url': 'https://api.github.com/users/meeseeksmachine/repos',
 'events_url': 'https://api.github.com/users/meeseeksmachine/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/meeseeksmachine/received_events',
 'type': 'User',
 'site_admin': False}

In [101]:
# We can convert one file format to another-
excel_df.to_json("attribute_dataset.json")

In [105]:
json_df.to_csv("url_csv.csv")

In [99]:
# We can read the xml data as well
xml_df = pd.read_xml("http://aiweb.cs.washington.edu/research/projects/xmltk/xmldata/data/auctions/321gone.xml")

In [100]:
# We can fetch the column names using .columns which is an attribute of the dataframe that we get
# after reading the file eg, read_csv()/read_xml() etc
xml_df.columns

Index(['seller_info', 'payment_types', 'shipping_info',
       'buyer_protection_info', 'auction_info', 'bid_history', 'item_info'],
      dtype='object')

In [113]:
xml_df.to_excel("xmltoexcel.xlsx",encoding="UTF-8",index=False)

In [111]:
xml_df

,seller_info,payment_types,shipping_info,buyer_protection_info,auction_info,bid_history,item_info
0,NaN,"Visa, Mastercard, , , , 0, Discover, American ...","siteonly, Buyer Pays Shipping Costs",NaN,NaN,NaN,NaN
1,NaN,Money Order,"International Shipping, See Shipping Description",NaN,NaN,NaN,NaN
2,NaN,"American Express, Discover, MasterCard, Visa","Other Shipping Service, UPS",NaN,NaN,NaN,NaN
3,NaN,"Visa, Mastercard, Personal Check, MOney Order,...","Irving, Utah, United States",NaN,NaN,NaN,NaN
4,NaN,"Visa, Mastercard, , , , 0, Discover, American ...","siteonly, Buyer Pays Shipping Costs",NaN,NaN,NaN,NaN
5,NaN,"Visa, Mastercard, Personal Check, , , 0, Disco...","International Shipping, Buyer Pays Shipping Costs",NaN,NaN,NaN,NaN
6,NaN,"Visa, Mastercard, Personal Check, , , 0, Disco...","International Shipping, Buyer Pays Shipping Costs",NaN,NaN,NaN,NaN
7,NaN,"American Express, Discover, Internet Escrow, i...","Buyer Pays Shipping Costs, FedEx, UPS",NaN,NaN,NaN,NaN
8,NaN,"American Express, C.O.D., Discover, Internet E...","Buyer Pays Shipping Costs, FedEx, Other Shippi...",NaN,NaN,NaN,NaN
9,NaN,Money Order,"International Shipping, See Shipping Description",NaN,NaN,NaN,NaN

In [112]:
excel_df.to_csv("excel_to_csv.csv",index=False)